service: covid-scoring-ms

plugins:
  - serverless-offline-python
  - serverless-python-requirements
  - serverless-dotenv-plugin

custom:
  pythonRequirements:
    dockerizePip: true
    zip: true
    layer: true

package:
  exclude:
    - venv/**
    - node_modules/**

provider:
  name: aws
  runtime: python3.6
  profile: 5vid-eb-deployment
  stage: prod

functions:
  score:
    handler: handler.score
    layers:
      - {Ref: PythonRequirementsLambdaLayer}
    events:
      - http:
          path: /score
          method: post
          cors: true
  
