import json
import traceback
from utils import Scorer

possible_answers = {'age': '27 - 59',
                    'bodyTemperature': '', 
                    'diagnosedWith_ASTHMA': False, 
                    'diagnosedWith_AUTOIMMUNEDISEASE': False, 
                    'diagnosedWith_KIDNEYDISEASE': False, 
                    'diagnosedWith_CHRONICLUNGDISEASE': False, 
                    'diagnosedWith_DIABETES': True, 
                    'diagnosedWith_HYPERTENSIONARTERIAL': True, 
                    'diagnosedWith_IMMUNOSUPRESSION': True, 
                    'diagnosedWith_CORONARYHEARTDISEASE': True, 
                    'hasBeenInContactWithInfected': False, 
                    'hasBeenTested': False, 
                    'isolationStatus': 'ISOLATION_DUE_TO_GOVERNMENT_ORDERS', ç
                    'name': 'Felipe Torres', 
                    'nationalId': '1152448890', 
                    'phone': '3215136527',
                    'postalCode': '050030', 
                    'score': -1, 
                    'sex': 'MALE', 
                    'IsPregnant': False, 
                    'smokingHabit': 'NEVER', 
                    'submissionTimestamp': 1585725018170, 
                    'symptomStart': '', 
                    'symptoms_DIARRHEA': False, 
                    'symptoms_DRY_COUGH': False, 
                    'symptoms_EXHAUSTION': False, 
                    'symptoms_FEVER': False, 
                    'symptoms_HEADACHE': False, 
                    'symptoms_HEAVY_BREATHING': False, 
                    'symptoms_MUSCLE_ACHING': False, 
                    'symptoms_NAUSEA_OR_VOMITING': False, 
                    'symptoms_NO_SMELL': False, 
                    'symptoms_NO_TASTE': False, 
                    'symptoms_RUNNY_NOSE': False, 
                    'symptoms_SLIME_COUGH': False, 
                    'symptoms_SORE_THROAT': False, 
                    'videoUrl': ''}
